### ISSUE TITLE
Live TV now playing not working with Kodi 19

### ISSUE THREAD

**Issue by powermarcel10** [Ghawken/FrontView#24]
Hi! 

I'm not sure since wich kodi version this bug started, but I think it was since the official release of Kodi 19. I'm sure it was working fine with Kodi 18.

Nowplaying information is not showing up in frontview when live TV is playing.

It stays on the homescreen. Is this a known issue?

Cheers,
Marcel

**Comment by Ghawken** [comment]
Hi
There a million ways to access "Live TV" and what is supported will depend on what way you are accessing.

Double check you have enabled:  Use currently playing when watching Movie/TV

How are you accessing live tv?

Have had a look and installed Demo PVR software - and can see the same issue - took a bit of tracking down but seems to relate to artwork changes in Kodi 20 (and presumably 19 from what you are seeing)

New Version
1.340 - being compiled now to hopefully address.  Still limited background artwork for channels, will use if provided otherwise will use thumb twice.  (same as before)
