### ISSUE TITLE
Details Screen Issue

### ISSUE THREAD

**Issue by xzener** [Ghawken/FrontView#5]
Glenn,

The details screen isn't displaying the cover as it was in previous versions. It is showing a fraction of the poster.jpg, just the very middle as if its zoomed in. Is this by design?

![capture](https://cloud.githubusercontent.com/assets/3745669/17464180/42ea4462-5c8d-11e6-82c5-b0c7fc8eec14.PNG)

**Comment by Ghawken** [comment]
Not by design.

Presume you have changed coverart setting to 'use original aspect ratio'. As per other issue ?

This causes this issue - and will soon have a effect on the cover flow - with bad clipping of the covers. (Depending on cache contents )

Need to update the skins to fix given change in file size (which I have done for both movies and tv. Fixing the above issue). Just trying to edit the xaml file manually to change layout of movies details screen (one above). Half way through it now, so can't post new version quite yet.  (As you found with changing a single variable in xaml,  changing xaml layout and making compatible with multiple screen sizes is a right pain)

Glenn

**Comment by Ghawken** [comment]
Fixed 1.162
